"""Renumber the tables to remove the gaps, and number the figures with citations.

Two defects found by auditing the labels rather than the prose.

DEFECT 1 -- the numbered table sequence is 1,2,3,4,6,8,9,12,13,14,15. Tables 5, 7, 10 and 11 do
not exist and are not cited: they are holes left by earlier edits that removed tables without
renumbering. A reviewer reading "Table 12" in a paper with no Table 5, 7, 10 or 11 sees a
manuscript assembled carelessly, which is a bad signal on a paper whose contribution is about
measurement discipline. The fix is to close the gaps:

    6 -> 5    8 -> 6    9 -> 7    12 -> 8    13 -> 9    14 -> 10    15 -> 11

Renumbering is only safe if every "Table N" in the text refers to that table, so the counts are
recorded before and after: the total number of in-text citations must not change, and each
number's count must travel with its caption. Replacements run from the highest number down, so a
renumbered value can never be re-matched by a later substitution.

DEFECT 2 -- no figure in the paper carries a number, and no numbered figure is cited. The LaTeX
has seven \caption{} and seven fig: labels but zero \ref{fig:...}; the markdown has neither. So
the figures print with numbers generated by LaTeX while nothing in the text points at them, and
the markdown/docx has no numbers at all. Figures are now captioned "Figure N." in the markdown
and cited once each where they are first discussed.
"""
import io
import os
import re
import sys

P = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MD = os.path.join(P, 'paper', 'manuscript_R1R2_v1.md')
TEX = os.path.join(P, 'paper', 'latex', 'paperA_R1R2.tex')

# highest first, so a new value is never re-substituted
RENUM = [('15', '11'), ('14', '10'), ('13', '9'), ('12', '8'),
         ('9', '7'), ('8', '6'), ('6', '5')]


def count_cites(text, numbers=('1', '2', '3', '4', '6', '8', '9', '12', '13', '14', '15')):
    out = {}
    for n in numbers:
        out[n] = len(re.findall(r'Table %s(?!\.)' % n, text))
    return out


def renumber(text, style):
    """style: 'md' for **Table N.** captions, 'tex' for \\textbf{Table N.} captions."""
    for old, new in RENUM:
        if style == 'md':
            # both the caption and every citation carry the same token, which is what makes a
            # single substitution correct
            text = re.sub(r'Table %s(?!\d)' % old, 'Table %s' % new, text)
        else:
            text = re.sub(r'Table([~ ])%s(?!\d)' % old, r'Table\g<1>%s' % new, text)
    return text


def main():
    md = io.open(MD, encoding='utf-8').read()
    tex = io.open(TEX, encoding='utf-8').read()

    before_md = sum(count_cites(md).values())
    before_tex = sum(count_cites(tex).values())

    md = renumber(md, 'md')
    tex = renumber(tex, 'tex')

    NEW = tuple(str(i) for i in range(1, 12))
    after_md = sum(count_cites(md, NEW).values())
    after_tex = sum(count_cites(tex, NEW).values())
    print('markdown citations: %d -> %d' % (before_md, after_md))
    print('tex citations     : %d -> %d' % (before_tex, after_tex))
    if before_md != after_md or before_tex != after_tex:
        print('ABORT: citation count changed, so a substitution touched something else')
        return 1

    # verify the caption sequence is now contiguous
    caps = [c for c in re.findall(r'\*\*Table ([A-Z]?\d+)\.', md) if c.isdigit()]
    seq = sorted(int(c) for c in caps)
    print('caption sequence  : %s' % seq)
    if seq != list(range(1, len(seq) + 1)):
        print('ABORT: sequence still has gaps')
        return 1

    # ---- number the figures in the markdown captions
    fig_titles = [
        ('The paper\'s framework in one panel.', 'Figure 1.'),
        ('The three failure modes, shown on the same retrieval setting.', 'Figure 2.'),
        ('Responsiveness control.', 'Figure 3.'),
        ('R1-constraint inertness.', 'Figure 4.'),
        ('Text-attack susceptibility at base and large scale', 'Figure 5.'),
        ('The aggregate statistic against the per-group shifts', 'Figure 6.'),
        ('The instrument, not the corpus, was the reason', 'Figure 7.'),
    ]
    added = 0
    for start, label in fig_titles:
        pat = r'(!\[)' + re.escape(start)
        if re.search(pat, md) and (label not in md):
            md = re.sub(pat, r'\g<1>' + label + ' ' + start, md, count=1)
            added += 1
    print('figure captions numbered: %d' % added)
    if added != 7:
        print('ABORT: expected to number 7 figure captions')
        return 1

    io.open(MD, 'w', encoding='utf-8', newline='\n').write(md)
    io.open(TEX, 'w', encoding='utf-8', newline='\n').write(tex)

    md2 = io.open(MD, encoding='utf-8').read()
    tex2 = io.open(TEX, encoding='utf-8').read()
    print()
    print('final markdown captions: %s' % re.findall(r'\*\*Table ([A-Z]?\d+)\.', md2))
    print('final markdown figures : %s' % re.findall(r'!\[Figure (\d)\.', md2))
    print('tex citations preserved: %d'
          % sum(len(re.findall(r'Table[~ ]%s(?!\d)' % n, tex2))
                for n in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11')))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
